[package]
name = "silicium-x86_64"
version = "0.1.0"
edition = "2021"

[dependencies]
arch-macros = { path = "macros", package = "macros" }
bitfield = { workspace = true }
macros = { workspace = true }
spin = { workspace = true }
log = { workspace = true }
limine = "0.2.0"

[lints]
workspace = true
