[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "arch/*",
  "crates/*"
]

[dependencies]
arch = { path = "arch/silicium-hal", package = "silicium-hal" }
log = "0.4.20"

[features]
default = ["logging"]
logging = ["arch/logging"]

[profile.release]
codegen-units = 1
opt-level = "s"
strip = true
lto = true

