[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "arch/silicium-hal",
  "arch/silicium-x86_64",
  "arch/silicium-x86_64/crates/*",
  "crates/*"
]

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"
inline_asm_x86_att_syntax = "deny"
if_then_some_else_none = "deny"
pedantic = "deny"
all = "deny"

[workspace.dependencies]
macros = { path = "crates/silicium-macros", package = "silicium-macros" }
spin = { path = "crates/silicium-spin", package = "silicium-spin" }
bitfield = "0.14.0"
bitflags = "2.4.2"
tailcall = "1.0.1"
log = "0.4.20"

[dependencies]
arch = { path = "arch/silicium-hal", package = "silicium-hal" }
macros = { workspace = true }
spin = { workspace = true }
log = { workspace = true }

[features]
default = ["panic_info", "logging"]

# Enable panic messages at the cost of increased binary size, but useful for debugging
panic_info = ["logging"]

# Enable logging at the cost of reduced performance and increased binary size
logging = ["arch/logging"]

[profile.release]
codegen-units = 1
opt-level = "s"
lto = true

