[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "arch/*", "crates/silicium-spin",
]

[dependencies]
arch = { path = "arch/silicium-hal", package = "silicium-hal" }

[features]
default = ["logging"]
logging = []

