[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "arch/silicium-arch-example",
    "arch/silicium-hal",
    "arch/silicium-x86_64",
    "crates/*",
]

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"
inline_asm_x86_att_syntax = "deny"
if_then_some_else_none = "deny"
pedantic = "deny"
all = "deny"

[workspace.dependencies]
macros = { path = "crates/silicium-macros", package = "silicium-macros" }
config = { path = "crates/silicium-config", package = "silicium-config" }
boot = { path = "crates/silicium-boot", package = "silicium-boot" }
addr = { path = "crates/silicium-addr", package = "silicium-addr" }
spin = { path = "crates/silicium-spin", package = "silicium-spin" }
arrayvec = { version = "0.7.4", default-features = false }
talc = { version = "4.3.1", features = ["counters"] }
static_assertions = "1.1.0"
bitfield = "0.14.0"
bitflags = "2.4.2"
tailcall = "1.0.1"
limine = "0.2"
log = "0.4.20"

[dependencies]
arch = { path = "arch/silicium-hal", package = "silicium-hal" }
bitflags = { workspace = true }
macros = { workspace = true }
config = { workspace = true }
addr = { workspace = true }
boot = { workspace = true }
spin = { workspace = true }
talc = { workspace = true }
log = { workspace = true }

[features]
default = ["panic_info", "logging"]

# Enable panic messages at the cost of increased binary size, but useful for debugging
panic_info = ["arch/panic_info"]

# Enable logging at the cost of reduced performance and increased binary size
logging = ["arch/logging"]

[profile.release]
codegen-units = 1
opt-level = "s"
lto = true
