[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "arch/*",
  "crates/*"
]

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"
inline_asm_x86_att_syntax = "deny"
if_then_some_else_none = "deny"
pedantic = "deny"
all = "deny"

[workspace.dependencies]
macros = { path = "crates/silicium-macros", package = "silicium-macros" }
spin = { path = "crates/silicium-spin", package = "silicium-spin" }
log = "0.4.20"

[dependencies]
arch = { path = "arch/silicium-hal", package = "silicium-hal" }
macros = { workspace = true }
spin = { workspace = true }
log = { workspace = true }

[features]
default = []
logging = ["arch/logging"]

[profile.release]
codegen-units = 1
opt-level = "s"
strip = true
lto = true

