name: Deploy

on:
  workflow_run:
    workflows: ["Rust"]
    branch: [master]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy documentation
        id: deployment
        uses: actions/deploy-pages@v4

