name: Deploy

on:
  workflow_run:
    workflows: ["Rust"]
    branch: [master]
    types:
      - completed

jobs:
  
  generate-docs:
    name: Generate documentation
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install rust toolchain
      run: rustup toolchain install nightly

    - name: Install mdbook
      run: cargo +nightly install mdbook

    - name: Generate documentation
      run: make build-docs

    - name: Generate book
      run: make build-book

    - name: Move build artifacts
      run: |
        rm -rf ./site/docs
        mv ./docs ./site/

    - name: Fix permissions
      run: chmod -c -R +rX "site/"

    - name: Upload documentation
      uses: actions/upload-pages-artifact@v3
      with:
        path: "site/" 

  deploy:
    name: Deploy
    needs: generate-docs

    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy documentation
        id: deployment
        uses: actions/deploy-pages@v4

