name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: lld
        version: 1.0
  
    - name: Check formatting
      run: make check-format

    - name: Check clippy
      run: make check-clippy

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: lld
        version: 1.0

    - name: Build kernel
      run: make build-kernel

    - name: Build servers
      run: make build-servers

    - name: Build user-space
      run: make build-userspace
  
  unit-tests:
    name: Unit tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: lld
        version: 1.0

    - name: Kernel unit tests
      run: make unit-tests-kernel

    - name: Servers unit tests
      run: make unit-tests-servers

    - name: Userspace unit tests
      run: make unit-tests-userspace

  integration-tests:
    name: Integration tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: lld qemu-system-x86
        version: 1.0
    
    - name: Silicium integration tests (Kernel and userspace)
      run: make integration-tests

